---
title: "Hydroelectrical Generation in México"
author: "Bruno Gonzalez"
date: "October 17, 2016"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Introduction

The following plot shows the electrical generation made by all the Hydroelectrical Plants in Mexico this year. You can interact with the plot choosing the month to analyze with the sidebar.

##UI

In the UI I defined the sidebar and the look of the app.

```{r, message=FALSE}

library(shiny)
library(plotly)

sliderInput("slider1", "Choose a Month:", min = 1, max = 12, value = 1)

```

##Server

On the server side, first I read the data, manipulated it and filter by month.

```{r}

days_m <- reactive({
  hydro_gen <- read.csv("generacionHidro.csv")
  hydro_gen$FECHA <- as.Date(hydro_gen$FECHA, "%d/%m/%y")
  month <- sprintf("%02d",input$slider1)
  hydro_month <- subset(hydro_gen, format.Date(FECHA, "%m")== month)
  dup <- duplicated(format.Date(hydro_month$FECHA, "%d"))
  days <- format.Date(hydro_month[!dup,]$FECHA, "%d")
  matrix(hydro_month$TOTAL, nrow = 24, ncol = length(days))
})

renderPlotly({
  plot_ly(z=days_m(), type="surface") %>%
  layout(
    scene =
      list(
        xaxis = list(title="Days"),
        yaxis = list(title="Hours"),
        zaxis = list(title="MWh", range=c(0,9000))
    ),
    autosize=F, width=1000, height=800
  )
})

```







