---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
  pdf_document: default
  word_document: default
---
echo = TRUE

## Loading and preprocessing the data

```{r}
data <- read.csv(unzip("activity.zip"))
data$date <- as.Date(data$date)
```



## What is mean total number of steps taken per day?


```{r}
num_steps <- aggregate(data$steps, by = list(Category = data$date), FUN = sum, na.rm = TRUE)
plot(num_steps, type = "h", lwd = 4)

mean_steps <- aggregate(data$steps, by = list(Category = data$date), FUN = mean, na.rm = TRUE)
median_steps <- aggregate(data$steps, by = list(Category = data$date), FUN = median, na.rm = TRUE)
mm_steps <- merge(mean_steps, median_steps, by.x = "Category", by.y = "Category")
mm_steps
```

## What is the average daily activity pattern?

There's a peak on the interval 865

```{r}
mean_interval <- aggregate(data$steps, by = list(Category = data$interval), FUN = mean, na.rm = TRUE)
plot(mean_interval$Category, mean_interval$x, type = "l")

max_steps <- max(mean_interval$x)
mean_interval[mean_interval$x == max_steps,]
```


## Imputing missing values

```{r}
na_steps <- is.na(data)
sum(na_steps)

c_data <- data

for (i in 1:17568){
  if(is.na(c_data$steps[i])) { c_data$steps[i]  <- mean_interval[mean_interval$Category == c_data$interval[i], 2]}

}


c_num_steps <- aggregate(c_data$steps, by = list(Category = c_data$date), FUN = sum, na.rm = TRUE)
plot(c_num_steps, type = "h", lwd = 4)

c_mean_steps <- aggregate(c_data$steps, by = list(Category = c_data$date), FUN = mean, na.rm = TRUE)
c_median_steps <- aggregate(c_data$steps, by = list(Category = c_data$date), FUN = median, na.rm = TRUE)
c_mm_steps <- merge(c_mean_steps, c_median_steps, by.x = "Category", by.y = "Category")
c_mm_steps
```

## Are there differences in activity patterns between weekdays and weekends?

Thera are more variability on the weekdays

```{r}

library(lattice)

wd <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
c_data$wd <- factor((weekdays(c_data$date) %in% wd), levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))

c_mean_interval <- aggregate(c_data$steps, by = list(steps = c_data$interval, day = c_data$wd), FUN = mean, na.rm = TRUE)
 xyplot(c_mean_interval$x ~ c_mean_interval$steps | c_mean_interval$day, type = "l")
 ```



